---
- name: Config playbook for production environment
  hosts: production       # Run the playbook for only the production devices
  connection: local
  gather_facts: false
  roles:
    - production
