---
- name: Gather Data
  hosts: all
  gather_facts: false
  become: false

  tasks:
    - name: Get CDP neighbors
      cisco.nxos.nxos_command:
        commands: show cdp neighbors
      register: my_neighbors
    
    - name: Get running config for vrf management
      cisco.nxos.nxos_command:
        commands: show run vrf management
      register: vrf_management_running

    - name: Store to file
      ansible.builtin.template:
        src: data.j2
        dest: gather_data_results
        mode: '0600'
