---
- name: Config playbook for both production and devtest environment
  hosts: devtest:production     # Run the playbook for both devtest and production devices
  gather_facts: false
  roles:
    - common
