---

- name: ntp authentication example
  hosts: n9k1
  connection: local
  gather_facts: no

  tasks:

    # Basic NTP authentication configuration
    - nxos_ntp_auth: state=present key_id=32 md5string=hello trusted_key=true auth_type=encrypt host={{ inventory_hostname }}
