---
- name: VLAN Interface Configuration Playbook
  hosts: all
  gather_facts: false
  vars_files:
    - external_vars.yml

  tasks:
    - name: Enable interface-vlan feature
      cisco.nxos.nxos_feature:
        feature: interface-vlan
        state: enabled

    - name: Create VLAN interfaces    # The task will execute for each item defined under vlan_interfaces variable
      cisco.nxos.nxos_interfaces:
        config:
          - name: "{{ item.name }}"
            description: "{{ item.desc }}"
            enabled: true
      loop:
        "{{ vlan_interfaces }}"

    - name: IPv4 Address configuration for the VLAN interfaces
      cisco.nxos.nxos_l3_interfaces:
        config:
          - name: "{{ vlan_interface.name }}"
            ipv4:
              - address: "{{ vlan_interface.ipv4 }}/{{ vlan_interface.mask }}"
      loop:
        "{{ vlan_interfaces }}"
      loop_control:
        loop_var: vlan_interface
