---

- name: NXOS_SAVE_CONFIG TESTING
  hosts: n9k2
  connection: local
  gather_facts: no


  tasks:
  - name: "SAVE CONFIG"
    nxos_save_config: host={{ inventory_hostname }}
    register: data

  - name: TEST 1
    assert:
      that:
        - data | changed
        - data.status == 'successful'

  - name: "ENSURE FAILS DUE TO BAD PATH FORMAT"
    nxos_save_config: path='bootflash=configs/my_config_test.cfg' host={{ inventory_hostname }}
    register: data
    ignore_errors: true

  - name: TEST 2
    assert:
      that:
        - data | failed

  # In order to be successful, the file shouldn't exist yet.
  - name: "SAVE CONFIG TO PATH"
    nxos_save_config: path='bootflash:configs/my_config_testing1.cfg' host={{ inventory_hostname }}
    register: data

  - name: TEST 3
    assert:
      that:
        - data | changed
        - data.path == 'bootflash:configs/my_config_testing1.cfg'

  # In order to be successful, the file should already exist. 
  - name: "ENSURE FAILS DUE TO ALREADY EXISTING FILE"
    nxos_save_config: path='bootflash:configs/my_config_test.cfg' host={{ inventory_hostname }}
    register: data
    ignore_errors: true

  - name: TEST 4
    assert:
      that:
        - data | failed

