---

- name: file copy testing
  hosts: n9k1
  connection: local
  gather_facts: no


  tasks:

  # Small file copy
  - name: Small file copy
    nxos_file_copy: source_file=test_files/smallfile host={{ inventory_hostname }}
    register: results

  # Small file copy
  - name: Small file copy idempotency
    nxos_file_copy: source_file=test_files/smallfile host={{ inventory_hostname }}
    register: results

  - assert:
      that:
        - "{{ results.changed ==false }}"

  # Large file copy
  - name: Large file copy
    nxos_file_copy: source_file=test_files/bigfile host={{ inventory_hostname }}
    register: results

  # Large file copy
  - name: Large file copy idempotency
    nxos_file_copy: source_file=test_files/bigfile host={{ inventory_hostname }}
    register: results

  - assert:
      that:
        - "{{ results.changed == false }}"
