---

- name: install config testing
  hosts: n9k1
  connection: local
  gather_facts: no

  tasks:

  # install config and get diff
  - name: install config and get diff
    nxos_install_config:
      source_config: test_files/myrollbackfile
      diff_file: diff_files/mydiff
      commit_changes: true
      host: "{{ inventory_hostname }}"
    register: results

  - assert:
      that:
        - results.source_config == 'test_files/myrollbackfile'
        - results.diff_file == 'diff_files/mydiff'
        - results.changed == true



