---

  - name: test playbook for nxos_igmp_snooping
    hosts: all
    gather_facts: no
    connection: local

    tasks:

       - name: ensure PIM is enabled
         nxos_feature:  feature=pim state=enabled host={{ inventory_hostname }}

       - name: ensure igmp_snooping is enabled and configured in the desired state
         nxos_igmp_snooping: group_timeout=30 snooping=true link_local_grp_supp=true optimize_mcast_flood=true v3_report_supp=true host={{ inventory_hostname }}
         register: data

       - name: Test 1
         assert:
           that:
             -  data.final.group_timeout == '30'
             -  data.final.snooping == true
             -  data.final.link_local_grp_supp == true
             -  data.final.optimize_mcast_flood == true
             -  data.final.v3_report_supp == true

       - name: ensure igmp_snooping is enabled and configured in the desired state
         nxos_igmp_snooping: group_timeout=30 snooping=true link_local_grp_supp=true optimize_mcast_flood=true v3_report_supp=true host={{ inventory_hostname }}
         register: data

       - name: Test 2 - verify idempotency
         assert:
           that:
             -  data.final.group_timeout == '30'
             -  data.final.snooping == true
             -  data.final.link_local_grp_supp == true
             -  data.final.optimize_mcast_flood == true
             -  data.final.v3_report_supp == true
             -  data.changed == false

       - name: ensure default option works for state param
         nxos_igmp_snooping: state=default host={{ inventory_hostname }}
         register: data

       - name: Test 3 - verify defaults
         assert:
           that:
             -  data.final.group_timeout == ''
             -  data.final.snooping == true
             -  data.final.link_local_grp_supp == true
             -  data.final.optimize_mcast_flood == true
             -  data.final.v3_report_supp == false
             -  data.changed == true

       - name: disable igmp snooping
         nxos_igmp_snooping: snooping=false host={{ inventory_hostname }}
         register: data

       - name: Test 4 - verify disable snooping
         assert:
           that:
             -  data.final.snooping == false
             -  data.changed == true
