---

- name: vtp testing
  hosts: n9k1
  connection: local
  gather_facts: no


  tasks:

  # set all three parameters
  - name: "Set all three VTP parameters"
    nxos_vtp: domain=ntc vtp_password=vpass version=1 host={{ inventory_hostname }}
    register: vtp_data

  - assert:
      that: 
        - "vtp_data['final']['domain'] == 'ntc'"
        - "vtp_data['final']['version'] == '1'"
        - "vtp_data['final']['vtp_password'] == 'vpass'"

  # Repeat idempotent operatio
  - name: "Set all three VTP parameters again to test idempotency"
    nxos_vtp: domain=ntc vtp_password=vpass version=1 host={{ inventory_hostname }}
    register: vtp_data

  - assert:
      that: 
        - "vtp_data['final']['domain'] == 'ntc'"
        - "vtp_data['final']['version'] == '1'"
        - "vtp_data['final']['vtp_password'] == 'vpass'"
        - "vtp_data['changed'] == false"

  # change just version
  - name: "Change just VTP version"
    nxos_vtp: version=2 host={{ inventory_hostname }}
    register: vtp_data

  - assert:
      that: 
        - "vtp_data['final']['domain'] == 'ntc'"
        - "vtp_data['final']['version'] == '2'"
        - "vtp_data['final']['vtp_password'] == 'vpass'"

  # no op
  - name: "Don't change anything"
    nxos_vtp: host={{ inventory_hostname }}
    register: vtp_data

  - assert:
      that: 
        - "vtp_data['final']['domain'] == 'ntc'"
        - "vtp_data['final']['version'] == '2'"
        - "vtp_data['final']['vtp_password'] == 'vpass'"

  # change just vtp_password
  - name: "Change just vtp password"
    nxos_vtp: vtp_password=vpass2 host={{ inventory_hostname }}
    register: vtp_data

  - assert:
      that: 
        - "vtp_data['final']['domain'] == 'ntc'"
        - "vtp_data['final']['version'] == '2'"
        - "vtp_data['final']['vtp_password'] == 'vpass2'"

  # change just domain
  - name: "Change just vtp domain"
    nxos_vtp: domain=mydomain host={{ inventory_hostname }}
    register: vtp_data

  - assert:
      that: 
        - "vtp_data['final']['domain'] == 'mydomain'"
        - "vtp_data['final']['version'] == '2'"
        - "vtp_data['final']['vtp_password'] == 'vpass2'"

  # remove password
  - name: "Remove vtp password"
    nxos_vtp: state=absent vtp_password=vpass2 host={{ inventory_hostname }}
    register: vtp_data

  - assert:
      that: 
        - "vtp_data['final']['domain'] == 'mydomain'"
        - "vtp_data['final']['version'] == '2'"
        - "vtp_data['final']['vtp_password'] != 'vpass2'"

  # remove wrong password
  - name: "Remove non-matching password. Should fail."
    nxos_vtp: state=absent vtp_password=edcba host={{ inventory_hostname }}
    ignore_errors: yes
    register: fail_object

  - assert:
      that: 
        - "fail_object['failed'] == true"

  # out of scope version number - should fail
  - name: "Change vtp version to impossible value. Should fail."
    nxos_vtp: version=99 host={{ inventory_hostname }}
    ignore_errors: yes
    register: fail_object

  - assert:
      that: 
        - "fail_object['failed'] == true"

  # can't remove domain name
  - name: "Remove domain name. Should fail."
    nxos_vtp: state=absent domain=test vtp_password=vpass2 host={{ inventory_hostname }}
    ignore_errors: yes
    register: fail_object

  - assert:
      that: 
        - "fail_object['failed'] == true"

  # can't remove version
  - name: "Remove vtp version. Should fail."
    nxos_vtp: state=absent version=1 vtp_password=vpass2 host={{ inventory_hostname }}
    ignore_errors: yes
    register: fail_object

  - assert:
      that: 
        - "fail_object['failed'] == true"



