---

  - name: nxos_vlan test playbook
    hosts: n9k1
    connection: local
    gather_facts: no

    tasks:

      - name: ENSURE NO VLANS EXIST ON THE SWITCH OTHER THAN VLAN 1
        nxos_vlan: vlan_range="2-3000" host={{ inventory_hostname }} state=absent
        register: data

      - name: TEST 1
        assert:
          that:
            - data.end_state_vlans_list == ['1']


      - name: ENSURE VLAN EXISTS WITH DESIRED ADMIN STATE / NAME
        nxos_vlan: vlan_id=50 host={{ inventory_hostname }} admin_state=down name=WEB
        register: data

      - name: TEST 2
        assert:
          that:
            - data | changed
            - data.end_state.vlan_id == '50'
            - data.end_state.name == 'WEB'
            - data.end_state.admin_state == 'down'
            - data.end_state.vlan_state == 'active'
            - data.existing_vlans_list == ['1']
            - data.end_state_vlans_list == ['1', '50']

      - name: ENSURE VLAN 50 DOES NOT EXIST ON THE SWITCH
        nxos_vlan: vlan_id=50 host={{ inventory_hostname }} state=absent
        register: data

      - name: TEST 3
        assert:
          that:
            - data | changed
            - data.existing_vlans_list == ['1', '50']
            - data.end_state_vlans_list == ['1']

      - name: ENSURE VLAN RANGE ADDS RESPECTIVE VLANs
        nxos_vlan: vlan_range="2-5,20,50,55-56" host={{ inventory_hostname }} state=present
        register: data

      - name: TEST 4
        assert:
          that:
            - data | changed
            - data.existing_vlans_list == ['1']
            - data.end_state_vlans_list == ['1', '2', '3', '4', '5', '20', '50', '55', '56']

      - name: IDEMPOTENCY CHECK
        nxos_vlan: vlan_range="2-5,20,50,55-56" host={{ inventory_hostname }} state=present
        register: data

      - name: TEST 5
        assert:
          that:
            - data.changed == false
            - data.end_state_vlans_list == ['1', '2', '3', '4', '5', '20', '50', '55', '56']

      - name: ENSURE VLAN 20 EXISTS WITH RESPECTIVE PARAMS
        nxos_vlan: vlan_id=20 host={{ inventory_hostname }} state=present name=app_vlan admin_state=down vlan_state=suspend
        register: data

      - name: TEST 6
        assert:
          that:
            - data | changed
            - data.end_state_vlans_list == ['1', '2', '3', '4', '5', '20', '50', '55', '56']
            - data.end_state.admin_state == 'down'
            - data.end_state.vlan_state == 'suspend'
            - data.end_state.name == 'app_vlan'

      - name: IDEMPOTENCY CHECK
        nxos_vlan: vlan_id=20 host={{ inventory_hostname }} state=present name=app_vlan admin_state=down vlan_state=suspend
        register: data

      - name: TEST 7
        assert:
          that:
            - data.changed == false
            - data.end_state_vlans_list == ['1', '2', '3', '4', '5', '20', '50', '55', '56']

      - name: ENSURE VLAN 60 EXISTS
        nxos_vlan: vlan_id=60 host={{ inventory_hostname }} state=present
        register: data

      - name: TEST 8
        assert:
          that:
            - data | changed
            - data.end_state_vlans_list == ['1', '2', '3', '4', '5', '20', '50', '55', '56', '60']
            - data.end_state.admin_state == 'up'
            - data.end_state.vlan_state == 'active'
            - data.end_state.name == 'VLAN0060'

      - name: IDEMPOTENCY CHECK
        nxos_vlan: vlan_id=60 host={{ inventory_hostname }} state=present
        register: data

      - name: TEST 9
        assert:
          that:
            - data.changed == false
            - data.end_state_vlans_list == ['1', '2', '3', '4', '5', '20', '50', '55', '56', '60']

      - name: ENSURE FAILURE WITH vlan_range and name
        nxos_vlan: vlan_range="2-5,20,50,55-56" host={{ inventory_hostname }} state=present name=test
        register: data
        ignore_errors: true

      - name: TEST 10
        assert:
          that:
            - data | failed


      - name: ENSURE FAILURE with vlan_id and vlan_range
        nxos_vlan: vlan_id=60 vlan_range=5-10 host={{ inventory_hostname }} state=present
        register: data
        ignore_errors: true

      - name: TEST 11
        assert:
          that:
            - data | failed

      - name: ENSURE SINGLE VALUE WORKS WITH vlan_range
        nxos_vlan: vlan_range=100 host={{ inventory_hostname }} state=present
        register: data

      - name: TEST 12
        assert:
          that:
            - data | changed
            - data.end_state_vlans_list == ['1', '2', '3', '4', '5', '20', '50', '55', '56', '60', '100']
            - data.end_state == None

      - name: ENSURE SAFE FAIL FOR VLAN ID THAT IS OUT OF RANGE
        nxos_vlan: vlan_id=5000 host={{ inventory_hostname }} state=present
        register: data
        ignore_errors: true

      - name: TEST 13
        assert:
          that:
            - data | failed
