---

  - name: test playbook for acl
    hosts: n9396-2.networktocode.com
    connection: local
    gather_facts: no

    tasks:

      - name: acl testing 1a
        nxos_acl:  name=MYACL seq=10 action=permit proto=tcp src=1.1.1.1/32 src_port_op=eq src_port1=80 dest=any log=enable established=enable host={{ inventory_hostname }}
        register: data

      - name: Test 1a
        assert:
          that:
            - data.final.name == 'MYACL'
            - data.final.seq == '10'
            - data.final.src == '1.1.1.1/32'
            - data.final.dest == 'any'
            - data.final.proto == 'tcp'
            - data.final.src_port_op == 'eq'
            - data.final.src_port1 == '80'
            - data.final.log == 'enable'
            - data.final.established == 'enable'

      - name: acl testing 1b
        nxos_acl:  name=MYACL seq=10 action=permit proto=tcp src=1.1.1.1/32 src_port_op=eq src_port1=80 dest=any log=enable established=enable host={{ inventory_hostname }}
        register: data

      - name: Test 1b - dempotency
        assert:
          that:
            - data.changed == false

      - name: acl testing 2
        nxos_acl:  name=MYACL seq=40 action=remark remark='COMMENT REMARK BY ANSIBLE' host={{ inventory_hostname }}
        register: data

      - name: Test 2
        assert:
          that:
            - data.final.remark == 'COMMENT REMARK BY ANSIBLE'
            - data.final.action == 'remark'
            - data.final.seq == '40'


      - name: acl testing 3
        nxos_acl:  name=MYACL seq=20 action=deny proto=udp src=2.1.1.1/20 src_port_op=neq src_port1=80 dest=5.5.5.0/24 dest_port_op=eq dest_port1=443 host={{ inventory_hostname }}
        register: data

      - name: Test 3
        assert:
          that:
            - data.final.name == 'MYACL'
            - data.final.seq == '20'
            - data.final.src == '2.1.1.1/20'
            - data.final.dest == '5.5.5.0/24'
            - data.final.proto == 'udp'
            - data.final.src_port_op == 'neq'
            - data.final.dest_port_op == 'eq'
            - data.final.src_port1 == '80'
            - data.final.dest_port1 == '443'

      - name: acl testing 4
        nxos_acl:  name=MYACL seq=25 action=permit proto=tcp src=10.1.1.1/32 src_port_op=range src_port1=20 src_port2=23 dest=192.168.0.0/16 host={{ inventory_hostname }}
        register: data

      - name: Test 4
        assert:
          that:
            - data.final.name == 'MYACL'
            - data.final.seq == '25'
            - data.final.src == '10.1.1.1/32'
            - data.final.dest == '192.168.0.0/16'
            - data.final.proto == 'tcp'
            - data.final.src_port_op == 'range'
            - data.final.src_port1 == '20'
            - data.final.src_port2 == '23'

      - name: acl testing 5
        nxos_acl:  name=MYACL seq=30 action=permit proto=tcp src=any dest=any dscp=af11 precedence=flash host={{ inventory_hostname }}
        ignore_errors: true
        register: data

      - name: Test 5
        assert:
          that:
            - data.failed == true


      - name: acl testing 5
        nxos_acl:  name=MYACL seq=30 action=permit proto=tcp src=any dest=any dscp=af11 host={{ inventory_hostname }}
        register: data

      - name: Test 5
        assert:
          that:
            - data.final.name == 'MYACL'
            - data.final.seq == '30'
            - data.final.action == 'permit'
            - data.final.src == 'any'
            - data.final.dest == 'any'
            - data.final.proto == 'tcp'
            - data.final.dscp == 'af11'

      - name: acl testing 6
        nxos_acl:  name=MYACL seq=20 state=absent host={{ inventory_hostname }}
        register: data

      - name: Test 6
        assert:
          that:
            - data.final == {}

      - name: acl testing 7
        nxos_acl:  name=MYACL state=delete_acl host={{ inventory_hostname }}
        register: data

      - name: Test 7
        assert:
          that:
            - data.final_acl == []


