---

- name: NXOS_GET_FACTS TESTING
  hosts: n9k2
  connection: local
  gather_facts: no


  tasks:
  - name: "RETRIEVE FACTS"
    nxos_get_facts: host={{ inventory_hostname }}
    register: data

  - name: "TEST 1"
    assert:
      that:
        - data

  - name: "RETRIEVE DETAILED FACTS"
    nxos_get_facts: host={{ inventory_hostname }} detail=true
    register: data

  - name: "TEST 2"
    assert:
      that:
        - data

  - name: "ENSURE FAIL DUE TO WRONG PARAM VALUE"
    nxos_get_facts: host={{ inventory_hostname }} detail=present
    register: data
    ignore_errors: true

  - name: "TEST 3"
    assert:
      that:
        - data | failed

  - name: ENSURE VLAN EXISTS WITH DESIRED ADMIN STATE / NAME
    nxos_vlan: vlan_id=211 host={{ inventory_hostname }} admin_state=down name=TESTING211
    register: data

  - name: TEST 4
    assert:
      that:
        - data | changed

  - name: "CONFIRM VLAN EXISTS WITH DESIRED NAME"
    nxos_get_facts: host={{ inventory_hostname }}
    register: data

  - name: TEST 5
    assert:
      that: data.ansible_facts.vlan_list[{{ item.0 }}].name == 'TESTING211'
    when: data.ansible_facts.vlan_list[{{ item.0 }}].vlan_id == '211'
    with_indexed_items: data.ansible_facts.vlan_list

  - name: ENSURE VLAN EXISTS WITH DESIRED ADMIN STATE / NAME
    nxos_vlan: vlan_id=212 host={{ inventory_hostname }} admin_state=down name=TESTING212
    register: data

  - name: TEST 6
    assert:
      that:
        - data | changed

  - name: "CONFIRM VLAN EXISTS WITH DESIRED ID"
    nxos_get_facts: host={{ inventory_hostname }}
    register: data

  - name: TEST 7
    assert:
      that: data.ansible_facts.vlan_list[{{ item.0 }}].vlan_id == '212'
    when: data.ansible_facts.vlan_list[{{ item.0 }}].name == 'TESTING212'
    with_indexed_items: data.ansible_facts.vlan_list

  - name: "CONFIRM ALL THE KEYS, INCLUDING DETAILED INFO, EXIST INSIDE RESULTS"
    nxos_get_facts: host={{ inventory_hostname }} detail=true
    register: data

  - name: "TEST 8"
    assert:
      that: 
        - data.ansible_facts.detailed_interface
        - data.ansible_facts.hostname
        - data.ansible_facts.interfaces
        - data.ansible_facts.fan_info
        - data.ansible_facts.kickstart
        - data.ansible_facts.module
        - data.ansible_facts.os
        - data.ansible_facts.platform
        - data.ansible_facts.power_supply_info
        - data.ansible_facts.rr 
        - data.ansible_facts.vlan_list

  - name: "CONFIRM ALL THE REQUIRED KEYS EXIST INSIDE RESULTS"
    nxos_get_facts: host={{ inventory_hostname }}
    register: data

  - name: "TEST 9"
    assert:
      that: 
        - data.ansible_facts.hostname
        - data.ansible_facts.interfaces
        - data.ansible_facts.fan_info
        - data.ansible_facts.kickstart
        - data.ansible_facts.module
        - data.ansible_facts.os
        - data.ansible_facts.platform
        - data.ansible_facts.power_supply_info
        - data.ansible_facts.rr 
        - data.ansible_facts.vlan_list

