---

- name: test playbook for nxos_vrrp
  hosts: n9396-2.networktocode.com
  connection: local
  gather_facts: no


  tasks:
    # prep for testing
    - nxos_feature: feature=vrrp state=enabled host={{ inventory_hostname }}
    - nxos_interface: interface=vlan10 state=absent host={{ inventory_hostname }}
    - nxos_interface: interface=vlan10 state=present host={{ inventory_hostname }}
    - nxos_ipv4_interface: interface=vlan10 ip_addr=10.1.100.2 mask=24 host={{ inventory_hostname }}

    - name: ensure vrrp group 100 and vip 10.1.100.1 is on vlan10
      nxos_vrrp: interface=vlan10 group=100 vip=10.1.100.1 host={{ inventory_hostname }}
      register: data

    - name: ensure config is correct
      assert:
        that:
          - data.final.group == '100'
          - data.final.vip == '10.1.100.1'


    - name: verifying idempotency
      nxos_vrrp: interface=vlan10 group=100 vip=10.1.100.1 host={{ inventory_hostname }}
      register: data

    - name: ensure config is correct
      assert:
        that:
          - data.final.group == '100'
          - data.final.vip == '10.1.100.1'
          - data.changed == false

    - name: ensure removal of the vrrp group config # vip is required to ensure the user knows what they are removing
      nxos_vrrp: interface=vlan10 group=100 vip=10.1.100.1 state=absent host={{ inventory_hostname }}
      register: data

    - name: ensure removal was successful
      assert:
        that:
          - data.final == {}
          - data.changed == true

    - name: re-config with more params
      nxos_vrrp: interface=vlan10 group=100 vip=10.1.100.1 preempt=false priority=130 auth=AUTHKEY host={{ inventory_hostname }}
      register: data

    - name: ensure config is correct
      assert:
        that:
          - data.final.group == '100'
          - data.final.vip == '10.1.100.1'
          - data.final.preempt == false
          - data.final.priority == '130'
          - data.final.auth == 'AUTHKEY'
          - data.changed == true

    - name: verifying idempotency
      nxos_vrrp: interface=vlan10 group=100 vip=10.1.100.1 preempt=false priority=130 auth=AUTHKEY host={{ inventory_hostname }}
      register: data

    - name: ensure config is correct
      assert:
        that:
          - data.changed == false


    # cleanup
    - name: ensure removal of the vrrp group config
      nxos_vrrp: interface=vlan10 group=100 vip=10.1.100.1 state=absent host={{ inventory_hostname }}
      register: data

    - name: ensure removal was successful
      assert:
        that:
          - data.final == {}
          - data.changed == true

    - nxos_interface: interface=vlan10 state=absent host={{ inventory_hostname }}
    - nxos_feature: feature=vrrp state=enabled host={{ inventory_hostname }}

