---

- name: ntp testing
  hosts: n9k1
  connection: local
  gather_facts: no

  tasks:

  # Set NTP Server
  - name: "Set NTP Server"
    nxos_ntp: server=1.2.3.4 host={{ inventory_hostname }}
    register: returned

  - assert:
      that:
        - "returned.final.address == '1.2.3.4'"
        - "returned.final.serv_peer == 'server'"

  # Set NTP Peer
  - name: "Set NTP Peer"
    nxos_ntp: peer=1.2.3.6 host={{ inventory_hostname }}
    register: returned

  - assert:
      that:
        - "returned.final.address == '1.2.3.6'"
        - "returned.final.serv_peer == 'peer'"

  # Set NTP Server with parameters
  - name: "Set NTP Server with parameters"
    nxos_ntp: server=1.2.3.4 key_id=32 prefer=enabled host={{ inventory_hostname }}
    register: returned

  - assert:
      that:
        - "returned.final.address == '1.2.3.4'"
        - "returned.final.serv_peer == 'server'"
        - "returned.final.prefer == 'enabled'"
        - "returned.final.key_id == '32'"

  # Subset of parameters for NTP Server results in no change
  - name: "Subset of parameters for NTP Server results in no change"
    nxos_ntp: server=1.2.3.4 key_id=32 host={{ inventory_hostname }}
    register: returned

  - assert:
      that:
        - "returned.final.address == '1.2.3.4'"
        - "returned.final.serv_peer == 'server'"
        - "returned.final.prefer == 'enabled'"
        - "returned.final.key_id == '32'"
        - "returned.changed == false"

  # New parameters for NTP Server don't corrupt old parameters
  - name: "New parameters for NTP Server don't corrupt old parameters"
    nxos_ntp: server=1.2.3.4 key_id=32 vrf_name=testing host={{ inventory_hostname }}
    register: returned

  - assert:
      that:
        - "returned.final.address == '1.2.3.4'"
        - "returned.final.serv_peer == 'server'"
        - "returned.final.prefer == 'enabled'"
        - "returned.final.key_id == '32'"
        - "returned.final.vrf_name == 'testing'"

  # NTP Server parameter (prefer) removal
  - name: "NTP Server parameter (prefer) removal"
    nxos_ntp: server=1.2.3.4 prefer=disabled host={{ inventory_hostname }}
    register: returned

  - assert:
      that:
        - "returned.final.address == '1.2.3.4'"
        - "returned.final.serv_peer == 'server'"
        - "returned.final.prefer == 'disabled'"
        - "returned.final.key_id == '32'"
        - "returned.final.vrf_name == 'testing'"
        - "returned.changed == true"

  # NTP Source address setting
  - name: " NTP Source address setting"
    nxos_ntp: source_addr=1.1.1.1 host={{ inventory_hostname }}
    register: returned

  - assert:
      that:
        - "returned.final.source_type == 'source'"
        - "returned.final.source_addr_int == '1.1.1.1'"

  # NTP Source address change
  - name: "NTP Source address change"
    nxos_ntp: source_addr=1.1.1.2 host={{ inventory_hostname }}
    register: returned

  - assert:
      that:
        - "returned.final.source_type == 'source'"
        - "returned.final.source_addr_int == '1.1.1.2'"
        - "returned.changed == true"

  # NTP Source interface setting
  - name: "NTP Source interface setting"
    nxos_ntp: source_int=vlan20 host={{ inventory_hostname }}
    register: returned

  - assert:
      that:
        - "returned.final.source_type == 'source-interface'"
        - "returned.final.source_addr_int == 'vlan20'"
        - "returned.changed == true"

  # Remove NTP Server
  - name: "Remove NTP Server"
    nxos_ntp: state=absent server=1.2.3.4 host={{ inventory_hostname }}
    register: returned

  - assert:
      that:
        - "'address' not in returned.final"

  # Remove NTP Server that doesn't exist
  - name: "Remove NTP Server that doesn't exist"
    nxos_ntp: state=absent server=1.2.3.4 host={{ inventory_hostname }}
    register: returned

  - assert:
      that:
        - "returned.changed == false"

  # Remove NTP source interface
  - name: "Remove NTP source interface"
    nxos_ntp: state=absent source_int=vlan20 host={{ inventory_hostname }}
    register: returned

  - assert:
      that:
        - "not returned.final.source_addr_int"


