---

  - name: test playbook for nxos_igmp_interface
    hosts: n9396-2.networktocode.com
    gather_facts: no
    connection: local

    tasks:

       - name: ensure PIM is enabled
         nxos_feature:  feature=pim state=enabled host={{ inventory_hostname }}

       - name: ensuring interface is a layer 3 interface before testing begins
         nxos_interface:  interface=eth1/32 mode=layer3 host={{ inventory_hostname }}

       - name: ensure pim is enabled on the interface
         nxos_pim_interface:  name=eth1/32 sparse=true host={{ inventory_hostname }}

       - name: ensure proper version of igmp is being used on the interface
         nxos_igmp_interface: name=Ethernet1/32 version=2 host={{ inventory_hostname }}
         register: data

       - assert:
           that:
             - data.final.version == '2'

       - name: ensure other params are configured properly
         nxos_igmp_interface: name=Ethernet1/32 startup_query_interval=35 query_mrt=10 immediate_leave=true report_llg=true host={{ inventory_hostname }}
         register: data

       - name: Test 2
         assert:
           that:
             - data.final.startup_query_interval == '35'
             - data.final.query_mrt == '10'
             - data.final.immediate_leave == true
             - data.final.report_llg == true

       - name: ensure more params are configured properly
         nxos_igmp_interface: name=Ethernet1/32 startup_query_count=4 robustness=2 querier_timeout=300 query_interval=125 last_member_qrt='2' group_timeout=265 last_member_query_count=2 host={{ inventory_hostname }}
         register: data

       - name: Test 3
         assert:
           that:
             - data.final.startup_query_count == '4'
             - data.final.robustness == '2'
             - data.final.querier_timeout == '300'
             - data.final.last_member_qrt == '2'
             - data.final.last_member_query_count == '2'
             - data.final.query_interval == '125'
             - data.final.group_timeout == '265'

       - name: use the state=default option
         nxos_igmp_interface: name=Ethernet1/32 state=default host={{ inventory_hostname }}
         register: data

       - name: Test 4 - verify defaults
         assert:
           that:
             - data.final.version == '2'
             - data.final.startup_query_interval == '31'
             - data.final.query_mrt == '10'
             - data.final.immediate_leave == false
             - data.final.report_llg == false
             - data.final.startup_query_count == '2'
             - data.final.robustness == '2'
             - data.final.querier_timeout == '255'
             - data.final.last_member_qrt == '1'
             - data.final.last_member_query_count == '2'
             - data.final.query_interval == '125'
             - data.final.group_timeout == '260'

       - name: Re-configure a few params to prep for the next test
         nxos_igmp_interface: name=Ethernet1/32 startup_query_count=4 robustness=2 querier_timeout=300 query_interval=125 last_member_qrt='2' group_timeout=265 last_member_query_count=2 host={{ inventory_hostname }}
         register: data

       - name: Test 5
         assert:
           that:
             - data.final.startup_query_count == '4'
             - data.final.robustness == '2'
             - data.final.querier_timeout == '300'
             - data.final.last_member_qrt == '2'
             - data.final.last_member_query_count == '2'
             - data.final.query_interval == '125'
             - data.final.group_timeout == '265'

       - name: config static joins with filters
         nxos_igmp_interface: name=Ethernet1/32 oif_prefix=239.0.0.0 oif_source=1.1.1.1 host={{ inventory_hostname }}
         register: data

       - name: Test 6
         assert:
           that:
             - data.final.oif_routemap == None # cannot have a routemap and prefix configured at the same time

       # NEED TO FIND A WAY TO TEST THIS SINCE oif_prefix_source is a list of dictionaries
       #- name: Test 7
       #  assert:
       #    that:
       #      - item.prefix == '239.0.0.0'
       #      - item.source == '1.1.1.1'
       #  with_items: data.final.oif_prefix_source
       #  tags:
       #    - this

       - name: config static join prefix
         nxos_igmp_interface: name=Ethernet1/32 oif_prefix=238.0.0.0 oif_source=1.1.1.1 host={{ inventory_hostname }}
         register: data

       - name: add another mcast prefix
         nxos_igmp_interface: name=Ethernet1/32 oif_prefix=237.0.0.0 host={{ inventory_hostname }}
         register: data

       - name: use routemap instead of prefix
         nxos_igmp_interface: name=Ethernet1/32 oif_routemap=MYROUTEMAP host={{ inventory_hostname }}
         ignore_errors: True
         register: data

       - name: ensure module fails since static entries are already configured
         assert:
           that:
             - data.failed == true

       - name: use the state=absent option = remove oif/prefix configs + defaults
         nxos_igmp_interface: name=Ethernet1/32 state=absent host={{ inventory_hostname }}
         register: data
         tags:
           - aaa

       - name: Test 7 - verify defaults
         assert:
           that:
             - data.final.version == '2'
             - data.final.startup_query_interval == '31'
             - data.final.query_mrt == '10'
             - data.final.immediate_leave == false
             - data.final.report_llg == false
             - data.final.startup_query_count == '2'
             - data.final.robustness == '2'
             - data.final.querier_timeout == '255'
             - data.final.last_member_qrt == '1'
             - data.final.last_member_query_count == '2'
             - data.final.query_interval == '125'
             - data.final.group_timeout == '260'
             - data.final.oif_prefix_source == []
             - data.final.oif_routemap == None
